---
title: "Seminario_UrkoPaulaVictoria"
author: "Urko Alli Barrena, Paula Gregorio Losada, Victoria Garcia Lovelle"
date: "`r Sys.Date()`"
output: html_document
---

## Carga de librerías:
```{r CargaLibrerías}
library(pdftools)
library(tidyverse)
library(tidyjson)
library(tidyr)
library(rjson) 
```

## Tabla de Esperanza de Vida:

```{r cargaDeDatosJson}
archivoJson <- fromJSON(file = "EsperanzaVida.json")

esperanzaVida <- spread_all(archivoJson)

# Para cada atributo me dice de qué tipo se trata
tibble1<-esperanzaVida %>% 
  gather_object %>%  
  json_types %>% 
  count(name, type)
```

```{r ObtencionTablaEsperanza}
#Viendo los arrays en el tibble 1, entro en el array Data, de éste puedo obtener el valor de la esperanza de vida, los años y el nombre de las comunidades Autónomas
arrayData<-esperanzaVida %>%
  enter_object(Data) %>% 
  gather_array %>% 
  spread_all %>% 
  select(Nombre, Anyo, Valor) 

partes <- strsplit(arrayData$Nombre, "\\.")

comunidadesAutonomas<-c()
for (i in partes){
  comunidadesAutonomas<-c(comunidadesAutonomas,i[1])
}

arrayData$Nombre<-comunidadesAutonomas

tablaComunidadesAñoValor<- as_tibble(arrayData)
attr(tablaComunidadesAñoValor, "JSON") <- NULL

tablaEsperanzaDeVida <- tablaComunidadesAñoValor %>%
  filter(Anyo==2020)%>%
  group_by(Anyo, Nombre) %>%
  summarize(EsperanzaDeVida = mean(Valor, na.rm = TRUE))%>%
  rename(Año=Anyo,ComunidadAutonoma=Nombre)

tablaEsperanzaDeVidaFinal <- tablaEsperanzaDeVida %>%
  mutate(ComunidadAutonoma = toupper(ComunidadAutonoma))

colnames(tablaEsperanzaDeVidaFinal) <- c("Anio", "ComunidadAutonoma", "EsperanzaDeVida")
tablaEsperanzaDeVidaFinal
```

## Tabla de Cantidad de Agua:

```{r CargaDatosCantidad}
archivoJsonCantidad <- fromJSON(file = "CantidadAgua.json")

cantidadAgua <- spread_all(archivoJsonCantidad)
```

```{r tablaCantidadAgua}
#Veo los tipos de atributos
cantidadAgua%>%
  gather_object%>%
  json_types%>%
  count(name,type)

#Entro en el array Data
arrayDataCantidad<-cantidadAgua%>%
  enter_object(Data)%>%
  gather_array%>%
  spread_all%>%
  select(-document.id,-array.index)

#Divido la cadena de texto nombre y solo cojo las comunidades autónomas
cadenas <- strsplit(arrayDataCantidad$Nombre, "\\,")

#Obtengo las comunidades autónomas
comunidadesAutonomasCantidad<-c()
for (i in cadenas){
  comunidadesAutonomasCantidad<-c(comunidadesAutonomasCantidad,i[1])
}


#Cambio la columna nombre por la columna de las comunidades autónomas
arrayDataCantidad$Nombre<-comunidadesAutonomasCantidad

#Tengo que eliminar de la tabla las comunidades autónomas donde ponga españa
tabla <- arrayDataCantidad %>%
  filter(!(Nombre == "España")) %>%
  select(Nombre, NombrePeriodo, Valor)

#Agrupo por comunidades autónomas y años
tablaCantidadDeAgua <- tabla %>%
  filter(NombrePeriodo  ==2020)%>%
  group_by(NombrePeriodo  , Nombre) %>%
  summarize(Cantidad = mean(Valor, na.rm = TRUE))%>%
  rename(Año=NombrePeriodo,ComunidadAutonoma=Nombre)

tablaCantidadDeAgua <- tablaCantidadDeAgua %>%
  mutate(ComunidadAutonoma = toupper(ComunidadAutonoma))

tablaCantidadDeAgua[4,2] <- c("BALEARS, ILLES")
tablaCantidadDeAgua[8,2] <- c("CASTILLA - LA MANCHA")
tablaCantidadDeAgua[14,2] <- c("MADRID, COMUNIDAD DE")
tablaCantidadDeAgua[15,2] <- c("MURCIA, REGIÓN DE")
tablaCantidadDeAgua[16,2] <- c("NAVARRA, COMUNIDAD FORAL DE")
tablaCantidadDeAgua[18,2] <- c("RIOJA, LA")

colnames(tablaCantidadDeAgua) <- c("Anio", "ComunidadAutonoma", "Cantidad")

tablaCantidadDeAguaFinal <- tablaCantidadDeAgua %>%
  mutate_at(vars(Anio), as.integer)
tablaCantidadDeAguaFinal

```


## Tabla de calidad de agua
```{r cargaDatosCalidadDeAgua}
ruta_pdf <- pdf_text("report_Cap.3_part2._Libro_blanco_del_agua.pdf")
pagina <- ruta_pdf[17]
lineas <- strsplit(pagina, "\n")[[1]]
linea_deseada <- lineas[5:21] 
```

```{r tablaCalidadDeAgua}
datos_divididos <- strsplit(linea_deseada, "\\s+")
datos_obtenidos <- datos_divididos[-c(1:3)]

datosDeInteres[[4]] <- c("CASTILLA - LA MANCHA","28","39","43","24","7","12","0")
datosDeInteres[[5]] <- c("CASTILLA Y LEÓN","2","2","2","0","1","1","0")
datosDeInteres[[9]] <- c("MADRID, COMUNIDAD DE","6","6","7","0","2","5","0")
datosDeInteres[[10]] <- c("MURCIA, REGIÓN DE","3","3","3","0","0","3","0")
```





